<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <LangVersion>12</LangVersion>
    <RootNamespace>Polymarket.Bot.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="3.15.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Polymarket.Bot.Domain\Polymarket.Bot.Domain.csproj" />
  </ItemGroup>

</Project>
