using Polymarket.Bot.Domain.Enums;
using Polymarket.Bot.Domain.ValueObjects;

namespace Polymarket.Bot.Domain.Entities;

/// <summary>
/// Represents a trading signal generated by a strategy.
/// </summary>
public class Signal : Entity
{
    public Guid MarketId { get; private set; }
    public Guid StrategyId { get; private set; }
    public SignalAction Action { get; private set; } = SignalAction.Skip;
    public decimal ModelProbability { get; private set; }
    public decimal MarketProbability { get; private set; }
    public decimal Edge { get; private set; }      // In decimal
    public decimal EdgeBps => Edge * 10000m;
    public decimal Confidence { get; private set; }
    public decimal SuggestedSize { get; private set; }
    public decimal KellyFraction { get; private set; }
    public string? Reasoning { get; private set; }
    public string? SkipReason { get; private set; }
    public List<string> PositiveFactors { get; private set; } = new();
    public List<string> NegativeFactors { get; private set; } = new();
    public List<string> BlockingFactors { get; private set; } = new();
    public DateTime GeneratedAt { get; private set; } = DateTime.UtcNow;

    // Navigation
    private Market? _market;
    public Market? Market => _market;

    private Strategy? _strategy;
    public Strategy? Strategy => _strategy;

    private Signal() { }

    public static Signal Create(
        Guid marketId,
        Guid strategyId,
        SignalAction action,
        decimal modelProbability,
        decimal marketProbability,
        decimal edge,
        decimal confidence,
        decimal suggestedSize = 0,
        decimal kellyFraction = 0,
        string? reasoning = null)
    {
        return new Signal
        {
            MarketId = marketId,
            StrategyId = strategyId,
            Action = action,
            ModelProbability = modelProbability,
            MarketProbability = marketProbability,
            Edge = edge,
            Confidence = confidence,
            SuggestedSize = suggestedSize,
            KellyFraction = kellyFraction,
            Reasoning = reasoning,
            GeneratedAt = DateTime.UtcNow
        };
    }

    public static Signal CreateSkip(
        Guid marketId,
        Guid strategyId,
        string reason,
        decimal? confidence = null)
    {
        return new Signal
        {
            MarketId = marketId,
            StrategyId = strategyId,
            Action = SignalAction.Skip,
            SkipReason = reason,
            Confidence = confidence ?? 0,
            GeneratedAt = DateTime.UtcNow
        };
    }

    public void AddFactors(
        IEnumerable<string>? positive = null,
        IEnumerable<string>? negative = null,
        IEnumerable<string>? blocking = null)
    {
        if (positive is not null) PositiveFactors.AddRange(positive);
        if (negative is not null) NegativeFactors.AddRange(negative);
        if (blocking is not null) BlockingFactors.AddRange(blocking);
    }

    public bool PassesThreshold(Strategy strategy)
    {
        if (Action == SignalAction.Skip) return false;

        var absEdge = Math.Abs(Edge);
        if (absEdge < strategy.MinEdgeBps / 10000m) return false;

        var entryPrice = Action == SignalAction.Buy ? MarketProbability : 1 - MarketProbability;
        if (entryPrice < strategy.EntryPriceThreshold - 0.05m) return false;

        return true;
    }
}
